# SPDX-License-Identifier: GPL-3.0-or-later
"""Generates the wiring diagrams in docs/hardware/wiring/.

Run it from the repository root after a change to the wiring:

    python3 tools/wiring_diagrams/generate.py
"""

from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "docs" / "hardware" / "wiring"
FONT = 'font-family="Helvetica, Arial, sans-serif"'
POWER = "#c45500"
GND = "#333"
SIGNAL = "#1f5fa8"
LOGIC = "#2e7d32"
MIC = "#2a7a8a"
BUTTON = "#6a1b9a"


def svg(width, height, title, body):
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" {FONT} font-size="13">
  <!-- SPDX-License-Identifier: GPL-3.0-or-later -->
  <!-- Generated by tools/wiring_diagrams/generate.py. Do not edit. -->
  <title>{title}</title>
  <rect x="0" y="0" width="{width}" height="{height}" fill="#ffffff"/>
  <defs>
    <marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0,0 L10,5 L0,10 z" fill="#333"/>
    </marker>
  </defs>
{body}</svg>
"""


def box(x, y, w, h, fill, stroke, dash=False):
    d = ' stroke-dasharray="6 4"' if dash else ""
    return (
        f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="6" fill="{fill}" '
        f'stroke="{stroke}" stroke-width="2"{d}/>\n'
    )


def text(x, y, s, size=13, anchor="middle", bold=False, fill="#222"):
    b = ' font-weight="bold"' if bold else ""
    return (
        f'  <text x="{x}" y="{y}" text-anchor="{anchor}" font-size="{size}"{b} '
        f'fill="{fill}">{s}</text>\n'
    )


def line(points, color, width=2.5, dash=False, arrow=False):
    d = ' stroke-dasharray="6 4"' if dash else ""
    a = ' marker-end="url(#arrow)"' if arrow else ""
    p = " ".join(f"{x},{y}" for x, y in points)
    return (
        f'  <polyline points="{p}" fill="none" stroke="{color}" '
        f'stroke-width="{width}"{d}{a}/>\n'
    )


def dot(x, y, color):
    return f'  <circle cx="{x}" cy="{y}" r="3.5" fill="{color}"/>\n'


def diode(x, y, color, pointing_left=False):
    """A diode symbol on a horizontal wire. The bar is the stripe (cathode)."""
    if pointing_left:
        return (
            f'  <polygon points="{x + 18},{y - 9} {x + 18},{y + 9} {x},{y}" fill="{color}"/>\n'
            f'  <line x1="{x - 2}" y1="{y - 11}" x2="{x - 2}" y2="{y + 11}" '
            f'stroke="{color}" stroke-width="3"/>\n'
        )
    return (
        f'  <polygon points="{x},{y - 9} {x},{y + 9} {x + 18},{y}" fill="{color}"/>\n'
        f'  <line x1="{x + 20}" y1="{y - 11}" x2="{x + 20}" y2="{y + 11}" '
        f'stroke="{color}" stroke-width="3"/>\n'
    )


def overview():
    b = ""
    b += box(20, 30, 170, 70, "#fff4d6", "#9a6b00")
    b += text(105, 58, "USB-C power", bold=True) + text(105, 78, "1 or 2 inputs", 11)
    b += text(105, 92, "Fig 4", 11, fill="#666")
    b += box(250, 30, 180, 70, "#ffe7cc", POWER)
    b += text(340, 58, "5 V bus", bold=True) + text(
        340, 78, "diodes, switch, branches", 11
    )
    b += text(340, 92, "Fig 4", 11, fill="#666")
    b += line([(190, 65), (250, 65)], POWER, 3, arrow=True)
    b += box(520, 20, 360, 100, "#f7d9d9", "#8b1a1a")
    b += text(700, 50, "N LED boards (1 to 16), in a ring", bold=True)
    b += text(700, 72, "8 columns × 32 rows each: 8 × N columns around", 11)
    b += text(700, 92, "board 1 → board 2 → … → board N", 11)
    b += text(700, 110, "Fig 3", 11, fill="#666")
    b += line([(430, 65), (520, 65)], POWER, 3, arrow=True) + text(
        475, 55, "power", 11, fill=POWER
    )
    b += box(250, 200, 180, 150, "#e0ecfb", SIGNAL)
    b += text(340, 228, "ESP32-S3-DevKitC-1", bold=True)
    b += text(340, 250, "5 V from the bus", 11) + text(340, 268, "through a 1N5819", 11)
    b += text(340, 336, "Fig 2", 11, fill="#666")
    b += line([(340, 100), (340, 200)], POWER, 2.5, arrow=True)
    b += box(520, 215, 170, 70, "#e3f0e3", LOGIC)
    b += text(605, 243, "74AHCT125", bold=True) + text(605, 263, "3.3 V to 5 V", 11)
    b += line([(430, 250), (520, 250)], LOGIC, 2.5, arrow=True)
    b += text(475, 240, "DIN CLK CS", 10, fill=LOGIC)
    b += line([(690, 250), (760, 250), (760, 120)], SIGNAL, 2.5, arrow=True)
    b += text(820, 190, "to the IN header", 10, fill=SIGNAL) + text(
        820, 204, "of board 1", 10, fill=SIGNAL
    )
    b += box(20, 180, 170, 50, "#efe3f6", BUTTON)
    b += text(105, 202, "USB controller", bold=True) + text(
        105, 220, '"USB" port, OTG adapter', 10
    )
    b += line([(190, 205), (250, 215)], BUTTON, 2.5, arrow=True)
    b += box(20, 250, 170, 50, "#e8f4f8", MIC, dash=True)
    b += text(105, 272, "INMP441 mic", bold=True) + text(
        105, 290, "optional, 3.3 V", 10
    )
    b += line([(190, 275), (250, 275)], MIC, 2.5)
    b += box(20, 320, 170, 50, "#f3eefb", BUTTON, dash=True)
    b += text(105, 342, "Mode button", bold=True) + text(105, 360, "optional", 10)
    b += line([(190, 345), (250, 330)], BUTTON, 2.5)
    b += text(
        20,
        400,
        "Dashed boxes are optional. Fig 2: ESP32-S3 pins. Fig 3: board chain. Fig 4: power.",
        11,
        anchor="start",
        fill="#555",
    )
    return svg(900, 420, "Life Torus wiring overview", b)


def board_chain():
    b = ""
    top, h = 110, 230
    boards = [("1", 60), ("2", 200), ("3", 340), ("…", None), ("N−1", 560), ("N", 700)]
    for name, x in boards:
        if x is None:
            b += text(470, top + h / 2, "…", 36, fill="#8b1a1a")
            continue
        b += box(x, top, 100, h, "#f7d9d9", "#8b1a1a")
        b += text(x + 50, top + h / 2, "Board " + name, 14, bold=True)
        b += text(x + 50, top + h / 2 + 18, "32 × 8", 11)
        b += f'  <rect x="{x + 10}" y="{top + 8}" width="80" height="16" fill="#fff" stroke="#8b1a1a"/>\n'
        b += text(x + 50, top + 20, "OUT", 10)
        b += f'  <rect x="{x + 10}" y="{top + h - 24}" width="80" height="16" fill="#fff" stroke="#8b1a1a"/>\n'
        b += text(x + 50, top + h - 12, "IN", 10)
    for xa, xb in [(60, 200), (200, 340), (560, 700)]:
        b += line(
            [
                (xa + 80, top + 8),
                (xa + 80, top - 30),
                (xa + 120, top - 30),
                (xa + 120, top + h + 30),
                (xb + 20, top + h + 30),
                (xb + 20, top + h - 8),
            ],
            SIGNAL,
            arrow=True,
        )
    b += line([(420, top + 8), (420, top - 30), (450, top - 30)], SIGNAL, dash=True)
    b += line(
        [(490, top + h + 30), (580, top + h + 30), (580, top + h - 8)],
        SIGNAL,
        dash=True,
        arrow=True,
    )
    b += text(
        470,
        top - 40,
        "DOUT → DIN, CS → CS, CLK → CLK, from each board to the next",
        12,
        fill=SIGNAL,
    )
    for xa, xb in [(60, 200), (560, 700)]:
        b += line(
            [
                (xa + 30, top + 8),
                (xa + 30, top - 12),
                (xa + 110, top - 12),
                (xa + 110, top + h + 50),
                (xb + 40, top + h + 50),
                (xb + 40, top + h - 8),
            ],
            POWER,
            2,
            dash=True,
        )
    b += text(
        470,
        top + h + 68,
        "VCC and GND jumpers only inside a pair: 1 → 2, 3 → 4, … (orange, dashed)",
        12,
        fill=POWER,
    )
    b += line(
        [(20, top + h + 10), (20, top + h - 16), (70, top + h - 16)], LOGIC, arrow=True
    )
    b += text(20, top + h + 26, "from the", 10, anchor="start", fill=LOGIC)
    b += text(20, top + h + 38, "74AHCT125", 10, anchor="start", fill=LOGIC)
    for x, label in [(60, "branch 1"), (340, "branch 2"), (560, "last branch")]:
        b += line([(x + 50, top + h + 95), (x + 50, top + h - 8)], POWER, 3, arrow=True)
        b += text(x + 50, top + h + 110, label, 11, fill=POWER)
    b += text(470, 30, "Fig 3. Board chain for N boards (1 to 16)", 15, bold=True)
    b += text(
        470,
        52,
        "Each board stands upright: IN header at the bottom, OUT header at the top. The OUT header of board N stays free.",
        11,
        fill="#555",
    )
    b += text(
        470,
        top + h + 135,
        "Power: one branch to the IN header of each odd board (1, 3, 5, …). With an odd N, board N gets its own branch. Fig 4.",
        11,
        fill="#555",
    )
    return svg(940, 520, "Board chain for N boards", b)


def power():
    b = text(470, 30, "Fig 4. 5 V power distribution for N boards", 15, bold=True)
    b += box(20, 60, 170, 55, "#fff4d6", "#9a6b00")
    b += text(105, 83, "USB-C input 1", bold=True) + text(
        105, 102, "5.1 kΩ on CC1 and CC2", 10
    )
    b += box(20, 135, 170, 55, "#fffaea", "#9a6b00", dash=True)
    b += text(105, 158, "USB-C input 2", bold=True) + text(105, 177, "optional", 10)
    for y in (78, 153):
        b += line([(190, y), (240, y)], POWER, 3) + diode(240, y, POWER)
        b += line([(262, y), (300, y), (300, 115)], POWER, 3)
    b += text(251, 62, "SB560", 10) + text(251, 177, "SB560", 10) + dot(300, 115, POWER)
    b += (
        line([(300, 115), (330, 115)], POWER, 3)
        + dot(330, 115, POWER)
        + dot(372, 115, POWER)
    )
    b += f'  <line x1="330" y1="115" x2="368" y2="98" stroke="{POWER}" stroke-width="3"/>\n'
    b += text(351, 88, "power switch", 10) + text(351, 135, "optional", 10, fill="#666")
    b += line([(372, 115), (420, 115)], POWER, 3)
    b += box(420, 95, 150, 40, "#ffe7cc", POWER) + text(
        495, 120, "5 V lever connector", 11, bold=True
    )
    for y in (102, 177):
        b += line([(190, y), (210, y), (210, 210)], GND, 3)
    b += line([(210, 210), (420, 210)], GND, 3)
    b += box(420, 190, 150, 40, "#e6e6e6", GND) + text(
        495, 215, "GND lever connector", 11, bold=True
    )
    for x, label in [(640, "board 1"), (760, "board 3"), (880, "board N−1 (or N)")]:
        b += line([(570, 115), (x, 115), (x, 300)], POWER, arrow=True)
        b += line([(570, 210), (x - 20, 210), (x - 20, 300)], GND, arrow=True)
        b += f'  <rect x="{x - 32}" y="250" width="24" height="16" fill="#fff" stroke="#555"/>\n'
        b += text(x - 10, 315, label, 11)
    b += text(820, 140, "…", 28, fill=POWER) + text(
        700, 280, "1000 µF", 10, fill="#555"
    )
    b += text(
        760,
        345,
        "One 0.5 mm² branch (5 V and GND) per pair of boards: ⌈N / 2⌉ branches,",
        11,
        fill="#555",
    )
    b += text(
        760,
        362,
        "with a 1000 µF capacitor at the IN header of the odd board.",
        11,
        fill="#555",
    )
    b += line([(495, 135), (495, 160), (330, 160), (330, 270)], POWER, 2, arrow=True)
    b += text(250, 290, 'ESP32-S3 "5V" pin', 11, anchor="start")
    b += text(250, 306, "through a 1N5819 (Fig 2)", 10, anchor="start", fill="#555")
    b += line([(495, 230), (495, 250), (450, 250), (450, 330)], GND, 2, arrow=True)
    b += text(450, 345, "GND of the ESP32-S3,", 10) + text(
        450, 358, "74AHCT125 and mic", 10
    )
    b += text(
        20,
        390,
        "Above 8 boards: connect both USB-C inputs, and use more lever connectors (or a terminal strip) "
        "for the extra branches. 1.0 mm² from the inputs to the lever connectors.",
        11,
        anchor="start",
        fill="#555",
    )
    return svg(960, 410, "Power distribution for N boards", b)


def esp32_connections():
    b = text(
        500,
        28,
        "Fig 2. ESP32-S3-DevKitC-1 connections (header J1, the antenna at the top)",
        15,
        bold=True,
    )
    bx, top, step = 560, 60, 21
    j1 = [
        "3V3",
        "3V3",
        "RST",
        "GPIO4",
        "GPIO5",
        "GPIO6",
        "GPIO7",
        "GPIO15",
        "GPIO16",
        "GPIO17",
        "GPIO18",
        "GPIO8",
        "GPIO3",
        "GPIO46",
        "GPIO9",
        "GPIO10",
        "GPIO11",
        "GPIO12",
        "GPIO13",
        "GPIO14",
        "5V",
        "G",
    ]
    used = {
        "3V3",
        "GPIO4",
        "GPIO5",
        "GPIO6",
        "GPIO7",
        "GPIO10",
        "GPIO11",
        "GPIO12",
        "5V",
        "G",
    }
    b += box(bx, top - 10, 170, len(j1) * step + 50, "#e0ecfb", SIGNAL)
    b += text(bx + 100, top + len(j1) * step + 25, "ESP32-S3", 13, bold=True)
    ys = {}
    for i, name in enumerate(j1):
        y = top + 10 + i * step
        ys.setdefault(name, y)
        on = name in used and i != 1
        fill = SIGNAL if on else "#9aa9bd"
        b += (
            f'  <rect x="{bx - 6}" y="{y - 6}" width="12" height="12" fill="{fill}"/>\n'
        )
        b += text(
            bx + 12,
            y + 4,
            name,
            11,
            anchor="start",
            fill="#222" if on else "#8a96a6",
            bold=on,
        )
    b += text(
        bx + 160,
        top + len(j1) * step - 2,
        '"USB" port: controller',
        10,
        anchor="end",
        fill=BUTTON,
    )
    b += text(
        bx + 160,
        top + len(j1) * step + 12,
        '"UART" port: computer',
        10,
        anchor="end",
        fill="#555",
    )
    gnd_x = 500
    b += line([(bx - 6, ys["G"]), (gnd_x, ys["G"]), (gnd_x, 205)], GND)
    b += text(gnd_x + 6, 300, "GND", 10, anchor="start", fill=GND)

    # Microphone.
    b += box(200, 45, 220, 200, "#e8f4f8", MIC, dash=True)
    b += text(212, 100, "INMP441 (optional)", 12, anchor="start", bold=True)
    b += text(212, 118, "3.3 V only, not 5 V", 10, anchor="start", fill="#b3261e")
    for pin, gpio in [
        ("VDD", "3V3"),
        ("SCK", "GPIO4"),
        ("WS", "GPIO5"),
        ("SD", "GPIO6"),
    ]:
        y = ys[gpio]
        b += text(415, y + 4, pin, 11, anchor="end") + line(
            [(420, y), (bx - 6, y)], MIC
        )
    for k, pin in enumerate(["GND", "L/R"]):
        y = 212 + k * 18
        b += (
            text(415, y + 4, pin, 11, anchor="end")
            + line([(420, y), (gnd_x, y)], GND)
            + dot(gnd_x, y, GND)
        )
    b += text(212, 230, "L/R to GND:", 10, anchor="start", fill="#555")
    b += text(212, 242, "left channel", 10, anchor="start", fill="#555")

    # Mode button: GPIO7 to GND, internal pull-up.
    y7 = ys["GPIO7"]
    b += box(200, 262, 220, 86, "#f3eefb", BUTTON, dash=True)
    b += text(212, 284, "Mode button (optional)", 12, anchor="start", bold=True)
    b += text(212, 302, "normally open push button,", 10, anchor="start", fill="#555")
    b += text(212, 316, "no resistor needed", 10, anchor="start", fill="#555")
    b += line([(bx - 6, y7), (470, y7), (470, 330), (405, 330)], BUTTON)
    b += dot(405, 330, BUTTON) + dot(365, 330, BUTTON)
    b += f'  <line x1="365" y1="320" x2="405" y2="320" stroke="{BUTTON}" stroke-width="3"/>\n'
    b += f'  <line x1="385" y1="320" x2="385" y2="310" stroke="{BUTTON}" stroke-width="3"/>\n'
    b += line([(365, 330), (330, 330), (330, 360), (gnd_x, 360)], GND) + dot(
        gnd_x, 360, GND
    )

    # Level shifter.
    b += box(150, 372, 240, 205, "#e3f0e3", LOGIC)
    for name, gpio, out in [
        ("9  3A", "GPIO10", "8  3Y → CS"),
        ("2  1A", "GPIO11", "3  1Y → DIN"),
        ("5  2A", "GPIO12", "6  2Y → CLK"),
    ]:
        y = ys[gpio]
        b += text(385, y + 4, name, 11, anchor="end") + line(
            [(390, y), (bx - 6, y)], LOGIC
        )
        b += text(160, y + 4, out, 11, anchor="start", fill=SIGNAL)
        b += line([(150, y), (80, y)], SIGNAL, arrow=True)
    b += text(
        20, ys["GPIO10"] - 14, "to the IN header", 10, anchor="start", fill=SIGNAL
    )
    b += text(20, ys["GPIO10"] - 2, "of board 1", 10, anchor="start", fill=SIGNAL)
    b += text(160, 470, "74AHCT125 (DIP-14)", 12, anchor="start", bold=True)
    b += text(160, 492, "14 VCC → 5 V bus", 11, anchor="start")
    b += text(160, 508, "7 GND, 1 4 10 13 (OE), 12 (4A) → GND", 11, anchor="start")
    b += text(160, 524, "100 nF from pin 14 to pin 7", 11, anchor="start")
    b += text(
        160,
        548,
        "pin 1 at the notch, counter-clockwise",
        10,
        anchor="start",
        fill="#555",
    )

    # 5 V feed through a Schottky diode, stripe towards the board.
    y5 = ys["5V"]
    b += line([(bx - 6, y5), (452, y5)], POWER) + diode(432, y5, POWER)
    b += line([(432, y5), (410, y5)], POWER)
    b += text(443, y5 - 14, "1N5819", 10) + text(
        405, y5 + 4, "5 V bus", 11, anchor="end", fill=POWER
    )

    notes = [
        "Right header (J3): not used.",
        "Grey pins: not used.",
        "",
        "The stripe of the 1N5819",
        "faces the board.",
        "",
        "Change any GPIO in the",
        "firmware options.",
    ]
    for k, note in enumerate(notes):
        b += text(780, 120 + k * 16, note, 11, anchor="start", fill="#555")
    return svg(
        1000, 620, "ESP32-S3 connections: level shifter, microphone, mode button", b
    )


def resistor(x, y, color):
    """A small resistor on a horizontal wire, from x to x + 30."""
    return f'  <rect x="{x}" y="{y - 6}" width="30" height="12" fill="#fff" stroke="{color}" stroke-width="2"/>\n'


def ws2812_lines():
    b = text(
        480,
        30,
        "Fig 5. WS2812B data lines (example: 10 panels on 4 lines)",
        15,
        bold=True,
    )
    b += box(20, 70, 150, 330, "#e0ecfb", SIGNAL)
    b += text(95, 390, "ESP32-S3", bold=True)
    b += box(240, 70, 170, 330, "#e3f0e3", LOGIC)
    b += text(325, 390, "74AHCT125", bold=True)
    lines = [
        ("GPIO11", "2  1A", "3  1Y", ["1", "2", "3"], "#c62828"),
        ("GPIO12", "5  2A", "6  2Y", ["4", "5", "6"], "#2e7d32"),
        ("GPIO10", "9  3A", "8  3Y", ["7", "8"], "#1565c0"),
        ("GPIO13", "12  4A", "11  4Y", ["9", "10"], "#555"),
    ]
    for k, (gpio, pin_in, pin_out, panels, color) in enumerate(lines):
        y = 105 + k * 72
        b += text(160, y + 4, gpio, 11, anchor="end", bold=True)
        b += line([(170, y), (240, y)], LOGIC)
        b += text(248, y + 4, pin_in, 11, anchor="start")
        b += text(402, y + 4, pin_out, 11, anchor="end")
        b += line([(410, y), (440, y)], SIGNAL) + resistor(440, y, SIGNAL)
        b += text(455, y - 12, "330 Ω", 10)
        b += line([(470, y), (510, y)], SIGNAL, arrow=True)
        b += text(490, y + 22, f"line {k + 1}", 10, fill=color)
        for i, name in enumerate(panels):
            x = 510 + i * 140
            b += box(x, y - 24, 100, 48, "#fbeaf0", color)
            b += text(x + 50, y - 3, "Panel " + name, 12, bold=True)
            b += text(x + 50, y + 13, "8 × 32", 10, fill="#555")
            if i + 1 < len(panels):
                b += line([(x + 100, y), (x + 140, y)], SIGNAL, arrow=True)
                b += text(x + 120, y - 10, "DOUT", 8, fill="#555")
                b += text(x + 120, y + 20, "DIN", 8, fill="#555")
    notes = [
        "Pin 14 (VCC) to the 5 V bus, pin 7 and pins 1, 4, 10, 13 (OE) to GND, 100 nF from 14 to 7.",
        "Each panel: DIN on the input connector, DOUT on the output connector. The last DOUT of a line stays free.",
        "N panels split in ring order: N / 4 on each line, and the first lines get one more. 1 to 3 lines also work.",
        "Connect the GND of each panel to the GND bus (Fig 6). The data lines need a common GND.",
    ]
    for k, note in enumerate(notes):
        b += text(20, 430 + k * 17, note, 11, anchor="start", fill="#555")
    return svg(960, 505, "WS2812B data lines", b)


def ws2812_power():
    b = text(
        480,
        30,
        "Fig 6. WS2812B power: 1 to 3 USB-C inputs, a branch to each panel",
        15,
        bold=True,
    )
    for k in range(3):
        y = 60 + k * 70
        b += box(
            20, y, 170, 50, "#fff4d6" if k == 0 else "#fffaea", "#9a6b00", dash=k > 0
        )
        b += text(105, y + 22, f"USB-C input {k + 1}", bold=True)
        b += text(105, y + 39, "5.1 kΩ on CC1 and CC2" if k == 0 else "optional", 10)
        b += line([(190, y + 18), (240, y + 18)], POWER, 3) + diode(240, y + 18, POWER)
        b += text(251, y + 4, "SB560", 10)
        b += line([(262, y + 18), (300, y + 18)], POWER, 3) + dot(300, y + 18, POWER)
        b += line([(190, y + 38), (210, y + 38)], GND, 3) + dot(210, y + 38, GND)
    b += line([(300, 78), (300, 218)], POWER, 3)
    b += (
        line([(300, 148), (330, 148)], POWER, 3)
        + dot(330, 148, POWER)
        + dot(372, 148, POWER)
    )
    b += f'  <line x1="330" y1="148" x2="368" y2="131" stroke="{POWER}" stroke-width="3"/>\n'
    b += text(351, 121, "power switch", 10) + text(
        351, 168, "optional", 10, fill="#666"
    )
    b += line([(372, 148), (420, 148)], POWER, 3)
    b += box(420, 128, 150, 40, "#ffe7cc", POWER) + text(
        495, 153, "5 V lever connector", 11, bold=True
    )
    b += line([(210, 98), (210, 290), (420, 290)], GND, 3)
    b += box(420, 270, 150, 40, "#e6e6e6", GND) + text(
        495, 295, "GND lever connector", 11, bold=True
    )
    for x, label in [(650, "panel 1"), (760, "panel 2"), (900, "panel N")]:
        b += line([(570, 148), (x, 148), (x, 360)], POWER, arrow=True)
        b += line([(570, 290), (x - 20, 290), (x - 20, 360)], GND, arrow=True)
        b += f'  <rect x="{x - 32}" y="320" width="24" height="16" fill="#fff" stroke="#555"/>\n'
        b += text(x - 10, 378, label, 11)
    b += text(830, 175, "…", 28, fill=POWER) + text(
        710, 345, "1000 µF", 10, fill="#555"
    )
    b += line([(495, 168), (495, 210), (350, 210), (350, 350)], POWER, 2, arrow=True)
    b += text(250, 368, 'ESP32-S3 "5V" pin', 11, anchor="start")
    b += text(250, 384, "through a 1N5819 (Fig 2)", 10, anchor="start", fill="#555")
    notes = [
        "One 0.5 mm² branch (5 V and GND) to the power wires of each panel, with a 1000 µF capacitor at the panel.",
        "Do not feed the power from one panel to the next through the 3-pin data connectors.",
        "1.0 mm² from the inputs to the lever connectors (1.5 mm² with 3 inputs). Use more lever connectors for more panels.",
        "The firmware limits the LED current (default 4,500 mA). Two 3 A inputs for 10 panels. Refer to Power and Wiring.",
    ]
    for k, note in enumerate(notes):
        b += text(20, 420 + k * 17, note, 11, anchor="start", fill="#555")
    return svg(960, 495, "WS2812B power distribution", b)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "overview.svg").write_text(overview())
    (OUT / "board-chain.svg").write_text(board_chain())
    (OUT / "power.svg").write_text(power())
    (OUT / "esp32-connections.svg").write_text(esp32_connections())
    (OUT / "ws2812-lines.svg").write_text(ws2812_lines())
    (OUT / "ws2812-power.svg").write_text(ws2812_power())


if __name__ == "__main__":
    main()
